apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
data:
  custom_users.xml: |
    <yandex>
      <users>
        <admin>
          <password>{{ .Values.password }}</password>
          <networks>
            <ip>::/0</ip>
          </networks>
          <profile>default</profile>
          <quota>default</quota>
          <access_management>1</access_management>
        </admin>
      </users>
    </yandex>

