apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  clusterIP: None
  selector:
    app: clickhouse
  ports:
{{- range .Values.service.headless.ports }}
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
{{- end }}
